# Heat template which instantiates base resources for a BIGIP deployment,
# namely.
#  - keypair
#  - security group
#  - F5 server group
#  - Internal HA network
#
#  Template version 5.0.2 - 2017-03-17
#
#
heat_template_version: 2014-10-16

description: >
  HOT template to instantiate base shared resources for a BIGIP deployment

parameters:
  vnf_name:
    type: string
    description: Unique name for this VF instance
  bigip_ssh_key:
    type: string
    description: SSH public key
  # Deployment scaling parameters
  # Internal high availability network parameters
  bigip_int_ha_net_prefix_v4:
    type: string
    description: IPv4 subnet prefix for internal HA network
  bigip_int_ha_net_prefix_len_v4:
    type: number
    description: Prefix length of subnet associated with internal HA network
    constraints:
    - range: { min: 0, max: 31 }
      description: int_ha_net_plen must be between 0 and 31

resources:
  # Security Group
  shared_bigip_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security Group for BIGIP networks
      name:
        str_replace:
            template:  $VNF_NAME_bigip_secgroup_0
            params:
              $VNF_NAME:  { get_param: vnf_name }
      rules:
        - {"direction": "egress", "remote_ip_prefix": "0.0.0.0/0", "protocol": "tcp", "ethertype": "IPv4", "port_range_max": 65535, "port_range_min": 1}
        - {"direction": "egress", "remote_ip_prefix": "0.0.0.0/0", "protocol": "udp", "ethertype": "IPv4", "port_range_max": 65535, "port_range_min": 1}
        - {"direction": "egress", "remote_ip_prefix": "0.0.0.0/0", "protocol": "icmp", "ethertype": "IPv4"}
        - {"direction": "egress", "remote_ip_prefix": "::/0", "protocol": "icmp", "ethertype": "IPv6"}
        - {"direction": "egress", "remote_ip_prefix": "::/0", "protocol": "tcp", "ethertype": "IPv6", "port_range_max": 65535, "port_range_min": 1}
        - {"direction": "egress", "remote_ip_prefix": "::/0", "protocol": "udp", "ethertype": "IPv6", "port_range_max": 65535, "port_range_min": 1}
        - {"direction": "ingress", "remote_ip_prefix": "0.0.0.0/0", "protocol": "tcp", "ethertype": "IPv4", "port_range_max": 65535, "port_range_min": 1}
        - {"direction": "ingress", "remote_ip_prefix": "0.0.0.0/0", "protocol": "udp", "ethertype": "IPv4", "port_range_max": 65535, "port_range_min": 1}
        - {"direction": "ingress", "remote_ip_prefix": "0.0.0.0/0", "protocol": "icmp", "ethertype": "IPv4"}
        - {"direction": "ingress", "remote_ip_prefix": "::/0", "protocol": "icmp", "ethertype": "IPv6"}
        - {"direction": "ingress", "remote_ip_prefix": "::/0", "protocol": "tcp", "ethertype": "IPv6", "port_range_max": 65535, "port_range_min": 1}
        - {"direction": "ingress", "remote_ip_prefix": "::/0", "protocol": "udp", "ethertype": "IPv6", "port_range_max": 65535, "port_range_min": 1}

  # Keypair for use by BIGIP instances.
  shared_bigip_keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: $VNF_NAME_bigip_key_pair_0
          params:
            $VNF_NAME: { get_param: vnf_name }
      public_key: {get_param: bigip_ssh_key}
      save_private_key: false

  shared_bigip_server_group:
    type: OS::Nova::ServerGroup
    properties:
      name:
        str_replace:
            template: $VNF_NAME_bigip_server_group_0
            params:
              $VNF_NAME:  { get_param: vnf_name }
      policies: ['anti-affinity']

  # Internal HA network for deployment.
  #   This is a private network with all instances on the same isolated L2
  #   L2 subnet.  There is no requirement for routing in an IP sense which 
  #   means that there is no need for a default gateway  
  bigip_internal_ha_ipam_net_0:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name:
        str_replace:
          template: $VF_NAME_bigip_int_ha_ipam_net_0
          params:
            $VF_NAME: { get_param: vnf_name }

  shared_bigip_internal_ha_net_0:
    type: OS::ContrailV2::VirtualNetwork
    depends_on: [ bigip_internal_ha_ipam_net_0 ]
    properties:
      name:
        str_replace:
          template: $VF_NAME_bigip_int_ha_net_0
          params:
            $VF_NAME: { get_param: vnf_name }
      virtual_network_properties:
        virtual_network_properties_rpf: enable
      is_shared: false
      flood_unknown_unicast: true
      network_ipam_refs:
        - get_resource: bigip_internal_ha_ipam_net_0
      network_ipam_refs_data:
        - network_ipam_refs_data_ipam_subnets:
            - network_ipam_refs_data_ipam_subnets_subnet:
                network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: bigip_int_ha_net_prefix_v4 }
                network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: bigip_int_ha_net_prefix_len_v4 }
              network_ipam_refs_data_ipam_subnets_enable_dhcp: false

outputs:
  shared_bigip_server_group:
    description: BIGIP F5 Server group
    value: { get_resource: shared_bigip_server_group}

  shared_bigip_keypair:
    description: SSH keypair for deployment
    value: { get_resource: shared_bigip_keypair }

  shared_bigip_sec_groups:
    description: List of security groups to use for all network interfaces
    value: { get_resource: shared_bigip_secgroup }

  shared_bigip_int_ha_net_id:
    description: HA internal network for deployment
    value: { get_resource: shared_bigip_internal_ha_net_0 }
