heat_template_version: 2013-05-23

description: >
  Metaswitch EAS (Enhanced Application Server)

parameters:
  eas_names:
    type: comma_delimited_list
    description: Server name for the VM instance
  vnf_id:
    type: string
    description: Unique ID for this VF instance
  vf_module_id:
    type: string
    description: Unique ID for this VF_MODULE instance
  eas_image_name:
    type: string
    description: Master image_name volume id
  eas_flavor_name:
    type: string
    description: Server flavor
    constraints:
      - custom_constraint: nova.flavor
  vvm_key_id:
    type: string
    description: SSH key name
    constraints:
      - custom_constraint: nova.keypair
  availability_zone_0:
    type: string
    description: Availability Zone ID or Name
  sec_grp_vvm_0_id:
    type: string
    description: The ID of the security group
  mgmt_net_id:
    type: string
    description: Neutron UUID for the Management network
    constraints:
      - custom_constraint: neutron.network
  eas_mgmt_ips:
    type: comma_delimited_list
    description: List of Management network IP addresses for IPv4
  eas_mgmt_v6_ips:
    type: comma_delimited_list
    description: List of Management network ip addresses for IPv6
  sig_net_id:
    type: string
    description: Neutron UUID for the Signaling network
    constraints:
      - custom_constraint: neutron.network
  eas_sig_ips:
    type: comma_delimited_list
    description: List of Signaling network IP addresses for IPv4
  eas_sig_v6_ips:
    type: comma_delimited_list
    description: List of Signaling network IP addresses for IPv6
  media_net_id:
    type: string
    description: Neutron UUID for the Media network
    constraints:
      - custom_constraint: neutron.network
  eas_media_ips:
    type: comma_delimited_list
    description: List of Media network IP addresses for IPv4
  eas_media_v6_ips:
    type: comma_delimited_list
    description: List of Media network IP addresses for IPv6
  eas_num_instances:
    type: number
    description: number of instance of the VF_module

resources:
  eas_modules:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: eas_num_instances }
      resource_def:
        type: nested_1_mvm_eas.yaml
        properties:
          eas_names: { get_param: eas_names }
          vnf_id: { get_param: vnf_id }
          vf_module_id: { get_param: vf_module_id }
          eas_image_name: { get_param: eas_image_name }
          eas_flavor_name: { get_param: eas_flavor_name }
          vvm_key_id: { get_param: vvm_key_id }
          availability_zone_0: { get_param: availability_zone_0 }
          sec_grp_vvm_0_id: { get_param: sec_grp_vvm_0_id }
          mgmt_net_id: { get_param: mgmt_net_id }
          eas_mgmt_ips: { get_param: eas_mgmt_ips }
          eas_mgmt_v6_ips: { get_param: eas_mgmt_v6_ips }
          sig_net_id: { get_param: sig_net_id }
          eas_sig_ips: { get_param: eas_sig_ips }
          eas_sig_v6_ips: { get_param: eas_sig_v6_ips }
          media_net_id: { get_param: media_net_id }
          eas_media_ips: { get_param: eas_media_ips }
          eas_media_v6_ips: { get_param: eas_media_v6_ips }
          indx: "%index%"
