heat_template_version: 2013-05-23

description: >
  Metaswitch SMPPP (SMPPP Proxy)

parameters:
  smppp_names:
    type: comma_delimited_list
    description: Server name for the VM instance
  vnf_id:
    type: string
    description: Unique ID for this VF instance
  vf_module_id:
    type: string
    description: Unique ID for this VF_MODULE instance
  smppp_image_name:
    type: string
    description: Master image_name volume id
  smppp_flavor_name:
    type: string
    description: Server flavor
    constraints:
      - custom_constraint: nova.flavor
  vvm_key_id:
    type: string
    description: SSH key name
    constraints:
      - custom_constraint: nova.keypair
  availability_zone_0:
    type: string
    description: Availability Zone ID or Name
  sec_grp_vvm_0_id:
    type: string
    description: The ID of the security group
  mgmt_net_id:
    type: string
    description: Neutron UUID for the Management network
    constraints:
      - custom_constraint: neutron.network
  smppp_mgmt_ips:
    type: comma_delimited_list
    description: List of Management network IP addresses for IPv4
  smppp_mgmt_v6_ips:
    type: comma_delimited_list
    description: List of Management network ip addresses for IPv6
  sig_net_id:
    type: string
    description: Neutron UUID for the Signaling network
    constraints:
      - custom_constraint: neutron.network
  smppp_sig_ips:
    type: comma_delimited_list
    description: List of Signaling network IP addresses for IPv4
  smppp_sig_v6_ips:
    type: comma_delimited_list
    description: List of Signaling network IP addresses for IPv6
  media_net_id:
    type: string
    description: Neutron UUID for the Media network
    constraints:
      - custom_constraint: neutron.network
  smppp_media_ips:
    type: comma_delimited_list
    description: List of Media network IP addresses for IPv4
  smppp_media_v6_ips:
    type: comma_delimited_list
    description: List of Media network IP addresses for IPv6
  serv_net_id:
    type: string
    description: Neutron UUID for the Service network
    constraints:
      - custom_constraint: neutron.network
  smppp_serv_ips:
    type: comma_delimited_list
    description: List of Service network IP addresses for IPv4
  serv1_net_id:
    type: string
    description: Neutron UUID for the Service 1 network
    constraints:
      - custom_constraint: neutron.network
  smppp_serv1_ips:
    type: comma_delimited_list
    description: List of Service 1 network IP addresses for IPv4
  serv2_net_id:
    type: string
    description: Neutron UUID for the Service 2 network
    constraints:
      - custom_constraint: neutron.network
  smppp_serv2_ips:
    type: comma_delimited_list
    description: List of Service 2 network IP addresses for IPv4
  smppp_num_instances:
    type: number
    description: number of instance of the VF_module

resources:
  smppp_modules:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: smppp_num_instances }
      resource_def:
        type: nested_9_mvm_smppp.yaml
        properties:
          smppp_names: { get_param: smppp_names }
          vnf_id: { get_param: vnf_id }
          vf_module_id: { get_param: vf_module_id }
          smppp_image_name: { get_param: smppp_image_name }
          smppp_flavor_name: { get_param: smppp_flavor_name }
          vvm_key_id: { get_param: vvm_key_id }
          availability_zone_0: { get_param: availability_zone_0 }
          sec_grp_vvm_0_id: { get_param: sec_grp_vvm_0_id }
          mgmt_net_id: { get_param: mgmt_net_id }
          smppp_mgmt_ips: { get_param: smppp_mgmt_ips }
          smppp_mgmt_v6_ips: { get_param: smppp_mgmt_v6_ips }
          sig_net_id: { get_param: sig_net_id }
          smppp_sig_ips: { get_param: smppp_sig_ips }
          smppp_sig_v6_ips: { get_param: smppp_sig_v6_ips }
          media_net_id: { get_param: media_net_id }
          smppp_media_ips: { get_param: smppp_media_ips }
          smppp_media_v6_ips: { get_param: smppp_media_v6_ips }
          serv_net_id: { get_param: serv_net_id }
          smppp_serv_ips: { get_param: smppp_serv_ips }
          serv1_net_id: { get_param: serv1_net_id }
          smppp_serv1_ips: { get_param: smppp_serv1_ips }
          serv2_net_id: { get_param: serv2_net_id }
          smppp_serv2_ips: { get_param: smppp_serv2_ips }
          indx: "%index%"
