heat_template_version: 2013-05-23

description: >
  Metaswitch MVM SSS (Mobility Voicemail)

parameters:
  sss_names:
    type: comma_delimited_list
    description: Server name for the VM instance
  vnf_id:
    type: string
    description: Unique ID for this VF instance
  vf_module_id:
    type: string
    description: Unique ID for this VF_MODULE instance
  sss_image_name:
    type: string
    description: Master image_name volume id
  sss_flavor_name:
    type: string
    description: Server flavor
    constraints:
      - custom_constraint: nova.flavor
  vvm_key_id:
    type: string
    description: SSH key name
    constraints:
      - custom_constraint: nova.keypair
  availability_zone_0:
    type: string
    description: Availability Zone ID or Name
  sec_grp_vvm_0_id:
    type: string
    description: The ID of the security group
  mgmt_net_id:
    type: string
    description: Neutron UUID for the Management network
    constraints:
      - custom_constraint: neutron.network
  sss_mgmt_ips:
    type: comma_delimited_list
    description: List of Management network IP addresses for IPv4
  sss_mgmt_v6_ips:
    type: comma_delimited_list
    description: Management network ip address for ipv6
  sig_net_id:
    type: string
    description: Neutron UUID for the Signaling network
    constraints:
      - custom_constraint: neutron.network
  sss_sig_ips:
    type: comma_delimited_list
    description: List of Signaling network IP addresses for IPv4
  sss_sig_v6_ips:
    type: comma_delimited_list
    description: List of Signaling network IP addresses for IPv6
  media_net_id:
    type: string
    description: Neutron UUID for the Media network
    constraints:
      - custom_constraint: neutron.network
  sss_media_ips:
    type: comma_delimited_list
    description: List of Media network IP addresses for IPv4
  sss_media_v6_ips:
    type: comma_delimited_list
    description: List of Media network IP addresses for IPv6
  serv_net_id:
    type: string
    description: Neutron UUID for the Service network
    constraints:
      - custom_constraint: neutron.network
  sss_serv_ips:
    type: comma_delimited_list
    description: List of Service network IP addresses for IPv4
  serv1_net_id:
    type: string
    description: Neutron UUID for the Service 1 network
    constraints:
      - custom_constraint: neutron.network
  sss_serv1_ips:
    type: comma_delimited_list
    description: List of Service 1 network IP addresses for IPv4
  serv2_net_id:
    type: string
    description: Neutron UUID for the Service 2 network
    constraints:
      - custom_constraint: neutron.network
  sss_serv2_ips:
    type: comma_delimited_list
    description: List of Service 2 network IP addresses for IPv4
  indx:
    type: number
    description: Index of the current instance

resources:
  sss_mgmt_0_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: $SERVER_NAME_mgmt_port
          params:
            $SERVER_NAME: { get_param: [ sss_names, { get_param: indx } ] }
      network_id: { get_param: mgmt_net_id }
      security_groups: [{ get_param: sec_grp_vvm_0_id }]
      fixed_ips:
        - ip_address: { get_param: [ sss_mgmt_ips, { get_param: indx } ] }
        - ip_address: { get_param: [ sss_mgmt_v6_ips, { get_param: indx } ] }

  sss_sig_0_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: $SERVER_NAME_sig_port
          params:
            $SERVER_NAME: { get_param: [ sss_names, { get_param: indx } ] }
      network_id: { get_param: sig_net_id }
      security_groups: [{ get_param: sec_grp_vvm_0_id }]
      fixed_ips:
          - ip_address: { get_param: [ sss_sig_ips, { get_param: indx } ] }
          - ip_address: { get_param: [ sss_sig_v6_ips, { get_param: indx } ] }

  sss_media_0_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: $SERVER_NAME_media_port
          params:
            $SERVER_NAME: { get_param: [ sss_names, { get_param: indx } ] }
      network_id: { get_param: media_net_id }
      security_groups: [{ get_param: sec_grp_vvm_0_id }]
      fixed_ips:
        - ip_address: { get_param: [ sss_media_ips, { get_param: indx } ] }
        - ip_address: { get_param: [ sss_media_v6_ips, { get_param: indx } ] }

  sss_service_0_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: $SERVER_NAME_service_port
          params:
            $SERVER_NAME: { get_param: [ sss_names, { get_param: indx } ] }
      network_id: { get_param: serv_net_id }
      security_groups: [{ get_param: sec_grp_vvm_0_id }]
      fixed_ips:
        - ip_address: { get_param: [ sss_serv_ips, { get_param: indx } ] }

  sss_service1_0_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: $SERVER_NAME_serv1_port
          params:
            $SERVER_NAME: { get_param: [ sss_names, { get_param: indx } ] }
      network_id: { get_param: serv1_net_id }
      security_groups: [{ get_param: sec_grp_vvm_0_id }]
      fixed_ips:
        - ip_address: { get_param: [ sss_serv1_ips, { get_param: indx } ] }

  sss_service2_0_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: $SERVER_NAME_serv2_port
          params:
            $SERVER_NAME: { get_param: [ sss_names, { get_param: indx } ] }
      network_id: { get_param: serv2_net_id }
      security_groups: [{ get_param: sec_grp_vvm_0_id }]
      fixed_ips:
        - ip_address: { get_param: [ sss_serv2_ips, { get_param: indx } ] }

  sss_server_0:
    type: OS::Nova::Server
    properties:
      name: { get_param: [ sss_names, { get_param: indx } ] }
      image: { get_param: sss_image_name }
      flavor: { get_param: sss_flavor_name }
      key_name: { get_param: vvm_key_id }
      networks:
        - port: { get_resource: sss_mgmt_0_port }
        - port: { get_resource: sss_sig_0_port }
        - port: { get_resource: sss_media_0_port }
        - port: { get_resource: sss_service_0_port }
        - port: { get_resource: sss_service1_0_port }
        - port: { get_resource: sss_service2_0_port }
      availability_zone: { get_param: availability_zone_0 }
      metadata:
        vnf_id: { get_param: vnf_id }
        vf_module_id: { get_param: vf_module_id }
