# Template for instantiating
#  - 1 x HA BIGIP pair - A instance
#
# This template assumes that a base template stack has previously been
# created so that deployment wide resources such as server-groups have been
# defined.
#
heat_template_version: 2014-10-16

description: >
  HOT template to instantiate an A side F5 BIGIP and optionally partner it with the corresponding B side

parameters:
  # General VNF parameters
  vnf_id:
    type: string
    description: ID of VNF
  vf_module_id:
    type: string
    description: Unique ID for this VF Module instance
  # Availability zones
  availability_zone_0:
    type: string
    description: Availability zone for A instances.
  availability_zone_1:
    type: string
    description: Availability zone for B instances.
  shared_bigip_keypair:
    type: string
    description: Keypair to use for accessing this F5 instance
    constraints:
    - custom_constraint: nova.keypair
  shared_bigip_sec_groups:
    type: comma_delimited_list
    description: List of security groups to add on all interfaces.
  shared_bigip_server_group:
    type: string
    description: Server group to use for these VMs
  # Internal network parameters
  shared_bigip_int_ha_net_id:
    type: string
    description: HA network id
    constraints:
    - custom_constraint: neutron.network
  # Management network parameters
  mgmt_net_id:
    type: string
    description: Management network ID
    constraints:
    - custom_constraint: neutron.network
  oam_net_id:
    type: string
    description: Network ID of oam_protected network.
    constraints:
    - custom_constraint: neutron.network
  # core network parameters
  core_net_id:
    type: string
    description: Network ID of core _direct network.
    constraints:
    - custom_constraint: neutron.network
  # dmz network parameters
  dmz_net_id:
    type: string
    description: Network ID of dmz_protected network.
    constraints:
    - custom_constraint: neutron.network
  # BIGIP parameters
  f5_flavor_name:
    type: string
    description: Flavor to use for creating BIGIP VM instance
    constraints:
    - custom_constraint: nova.flavor
  f5_image_name:
    type: string
    description: Glance image to use for launching BIGIP F5 instances.
    constraints:
    - custom_constraint: glance.image
  f5_a_name_0:
    type: string
    description: Name of VM A of BIGIP
    constraints:
    - allowed_pattern: '[a-zA-Z0-9][a-zA-Z0-9-]{0,31}$'
      description: VM  name must be 32 characters or less and a valid hostname.  Only alphanumeric characters plus hyphen are allowed.
  # BIGIP names of the physical B instance
  f5_b_name_0:
    type: string
    description: Name of VM B of BIGIP
    constraints:
    - allowed_pattern: '[a-zA-Z0-9][a-zA-Z0-9-]{0,31}$'
      description: VM  name must be 32 characters or less and a valid hostname.  Only alphanumeric characters plus hyphen are allowed.
  # BIGIP IP addresses on management network
  f5_a_mgmt_ip_0:
    type: string
    description: Management fixed IP address to use for BIGIP A.
  f5_b_mgmt_ip_0:
    type: string
    description: Management fixed IP address to use for BIGIP B.
  # BIGIP IP addresses on internal HA network
  f5_a_int_ha_ip_0:
    type: string
    description: HA fixed IP address to use for BIGIP A.
  f5_b_int_ha_ip_0:
    type: string
    description: HA fixed IP address to use for BIGIP B.
  # BIGIP IP addresses on oam network
  f5_oam_vip_0:
    type: string
    description: ALP on oam network for BIGIP.
  f5_a_oam_ip_0:
    type: string
    description: Fixed IPv4 address on oam network for BIGIP A.
  # BIGIP IP addresses on core network
  f5_core_vip_0:
    type: string
    description: ALP on core network for BIGIP.
  f5_a_core_ip_0:
    type: string
    description: Fixed IPv4 address on core network for BIGIP A.
  # BIGIP IP addresses on dmz network
  f5_dmz_vip_0:
    type: string
    description: ALP on dmz network for BIGIP.
  f5_a_dmz_ip_0:
    type: string
    description: Fixed IPv4 address on dmz network for BIGIP A.
resources:
  # F5 BIGIP
  bigip:
    type: f5_a_child.yaml
    properties:
      vnf_id: { get_param: vnf_id }
      vm_role: 'f5'
      vf_module_id: { get_param: vf_module_id }
      f5_a_name_0: { get_param: f5_a_name_0 }
      bigip_image_name: { get_param: f5_image_name }
      bigip_flavor_name: { get_param: f5_flavor_name }
      bigip_keypair: { get_param: shared_bigip_keypair }
      availability_zone_0: { get_param: availability_zone_0 }
      availability_zone_1: { get_param: availability_zone_1 }
      mgmt_net_id: { get_param: mgmt_net_id }
      f5_a_mgmt_ip_0: { get_param: f5_a_mgmt_ip_0 }
      bigip_sec_groups: { get_param: shared_bigip_sec_groups }
      int_ha_net_id: { get_param: shared_bigip_int_ha_net_id }
      f5_a_int_ha_ip_0: { get_param: f5_a_int_ha_ip_0 }
      f5_b_int_ha_ip_0: { get_param: f5_b_int_ha_ip_0 }
      oam_net_id: { get_param: oam_net_id }
      f5_oam_vip_0: { get_param: f5_oam_vip_0 }
      f5_a_oam_ip_0: { get_param: f5_a_oam_ip_0 }
      core_net_id: { get_param: core_net_id }
      f5_core_vip_0: { get_param: f5_core_vip_0 }
      f5_a_core_ip_0: { get_param: f5_a_core_ip_0 }
      dmz_net_id: { get_param: dmz_net_id }
      f5_dmz_vip_0: { get_param: f5_dmz_vip_0 }
      f5_a_dmz_ip_0: { get_param: f5_a_dmz_ip_0 }
      bigip_server_group: { get_param: shared_bigip_server_group }
