# Template for instantiating
#  - 1 x HA F5 pair - B instance
#
# This template assumes that a base template stack has previously been
# created so that deployment wide resources such as server-groups have been
# defined.
#
heat_template_version: 2014-10-16

description: >
  HOT template to instantiate an B side BIPIP F5 

parameters:
  # General VNF parameters
  vnf_id:
    type: string
    description: ID of VNF
  vf_module_id:
    type: string
    description: Unique ID for this VF Module instance
  # Availability zones
  availability_zone_0:
    type: string
    description: Availability zone for A instances.
  availability_zone_1:
    type: string
    description: Availability zone for B instances.
  shared_bigip_keypair:
    type: string
    description: Keypair to use for accessing this BIPIP instance
    constraints:
    - custom_constraint: nova.keypair
  shared_bigip_sec_groups:
    type: comma_delimited_list
    description: List of security groups to add on all interfaces.
  shared_bigip_server_group:
    type: string
    description: Server group to use for these VMs
  # Internal network parameters
  shared_bigip_int_ha_net_id:
    type: string
    description: HA network id
    constraints:
    - custom_constraint: neutron.network
  # Management network parameters
  mgmt_net_id:
    type: string
    description: Management network ID
    constraints:
    - custom_constraint: neutron.network
  # oam network parameters
  oam_net_id:
    type: string
    description: Network ID of oam/core network.
    constraints:
    - custom_constraint: neutron.network
  # core network parameters
  core_net_id:
    type: string
    description: Network ID of core network.
    constraints:
    - custom_constraint: neutron.network
  # dmz network parameters
  dmz_net_id:
    type: string
    description: Network ID of dmz network.
    constraints:
    - custom_constraint: neutron.network
  # F5 parameters
  f5_flavor_name:
    type: string
    description: Flavor to use for creating F5 VM instance
    constraints:
    - custom_constraint: nova.flavor
  f5_image_name:
    type: string
    description: Glance image to use for launching F5 BIPIP instances.
    constraints:
    - custom_constraint: glance.image
  # F5 names of the physical B instance
  f5_b_name_0:
    type: string
    description: Name of VM B of F5
    constraints:
    - allowed_pattern: '[a-zA-Z0-9][a-zA-Z0-9-]{0,31}$'
      description: VM  name must be 32 characters or less and a valid hostname.  Only alphanumeric characters plus hyphen are allowed.
  #  description: Management virtual IP address to use for F5.
  f5_b_mgmt_ip_0:
    type: string
    description: Management fixed IP address to use for F5 B.
  # F5 IP addresses on internal HA network
  f5_b_int_ha_ip_0:
    type: string
    description: HA fixed IP address to use for F5 B.
  f5_a_int_ha_ip_0:
    type: string
    description: HA fixed IP address to use for F5 A.
  # F5 IP addresses on oam/core network
  f5_oam_vip_0:
    type: string
    description: Virtual IPv6 address on oam/core network for F5.
  f5_b_oam_ip_0:
    type: string
    description: Fixed IPv6 address on oam/core network for F5 B.
  # F5 IP addresses on core network
  f5_core_vip_0:
    type: string
    description: Virtual IPv6 address on core network for F5.
  f5_b_core_ip_0:
    type: string
    description: Fixed IPv6 address on core network for F5 B.
  # F5 IP addresses on dmz network
  f5_dmz_vip_0:
    type: string
    description: Virtual IPv6 address on dmz network for F5.
  f5_b_dmz_ip_0:
    type: string
    description: Fixed IPv6 address on dmz network for F5 B.

resources:
  # BIPIP F5
  bigip:
    type: f5_b_child.yaml
    properties:
      vnf_id: { get_param: vnf_id }
      vm_role: 'vf5'
      vf_module_id: { get_param: vf_module_id }
      f5_b_name_0: { get_param: f5_b_name_0 }
      bigip_image_name: { get_param: f5_image_name }
      bigip_flavor_name: { get_param: f5_flavor_name }
      bigip_keypair: { get_param: shared_bigip_keypair }
      availability_zone_0: { get_param: availability_zone_0 }
      availability_zone_1: { get_param: availability_zone_1 }
      mgmt_net_id: { get_param: mgmt_net_id }
      f5_b_mgmt_ip_0: { get_param: f5_b_mgmt_ip_0 }
      bigip_sec_groups: { get_param: shared_bigip_sec_groups }
      int_ha_net_id: { get_param: shared_bigip_int_ha_net_id }
      f5_b_int_ha_ip_0: { get_param: f5_b_int_ha_ip_0 }
      f5_a_int_ha_ip_0: { get_param: f5_a_int_ha_ip_0 }
      oam_net_id: { get_param: oam_net_id }
      f5_oam_vip_0: { get_param: f5_oam_vip_0 }
      f5_b_oam_ip_0: { get_param: f5_b_oam_ip_0 }
      core_net_id: { get_param: core_net_id }
      f5_core_vip_0: { get_param: f5_core_vip_0 }
      f5_b_core_ip_0: { get_param: f5_b_core_ip_0 }
      dmz_net_id: { get_param: dmz_net_id }
      f5_dmz_vip_0: { get_param: f5_dmz_vip_0 }
      f5_b_dmz_ip_0: { get_param: f5_b_dmz_ip_0 }
      bigip_server_group: { get_param: shared_bigip_server_group }
